/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WebtrainingPersonalCard {
        "personalDescription": string;
        "personalImg": string;
        "personalLastName": string;
        "personalName": string;
        "personalRole": string;
    }
    interface WebtrainingVideoPlayer {
        "provider": string;
        "videoSource": string;
    }
}
declare global {
    interface HTMLWebtrainingPersonalCardElement extends Components.WebtrainingPersonalCard, HTMLStencilElement {
    }
    var HTMLWebtrainingPersonalCardElement: {
        prototype: HTMLWebtrainingPersonalCardElement;
        new (): HTMLWebtrainingPersonalCardElement;
    };
    interface HTMLWebtrainingVideoPlayerElement extends Components.WebtrainingVideoPlayer, HTMLStencilElement {
    }
    var HTMLWebtrainingVideoPlayerElement: {
        prototype: HTMLWebtrainingVideoPlayerElement;
        new (): HTMLWebtrainingVideoPlayerElement;
    };
    interface HTMLElementTagNameMap {
        "webtraining-personal-card": HTMLWebtrainingPersonalCardElement;
        "webtraining-video-player": HTMLWebtrainingVideoPlayerElement;
    }
}
declare namespace LocalJSX {
    interface WebtrainingPersonalCard {
        "personalDescription"?: string;
        "personalImg"?: string;
        "personalLastName"?: string;
        "personalName"?: string;
        "personalRole"?: string;
    }
    interface WebtrainingVideoPlayer {
        "provider"?: string;
        "videoSource"?: string;
    }
    interface IntrinsicElements {
        "webtraining-personal-card": WebtrainingPersonalCard;
        "webtraining-video-player": WebtrainingVideoPlayer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "webtraining-personal-card": LocalJSX.WebtrainingPersonalCard & JSXBase.HTMLAttributes<HTMLWebtrainingPersonalCardElement>;
            "webtraining-video-player": LocalJSX.WebtrainingVideoPlayer & JSXBase.HTMLAttributes<HTMLWebtrainingVideoPlayerElement>;
        }
    }
}
